name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  merge_group:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build
      run: echo 'Test'
